# Site settings
title: GroupGets on GitHub.io
email: contact@groupgets.com
description: > # this means to ignore newlines until "baseurl:"
  GroupGets is a crowd purchasing site where you can create or join
  group buys for anything that exists.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://groupgets.github.io" # the base hostname & protocol for your site
website_name: GroupGets.com
website_url: "https://groupgets.com" # the base hostname & protocol for your site
twitter_username: groupgetscom
github_username:  groupgets

# Build settings
markdown: kramdown
